language: node.js
node_js:
  - "10"
before_script:
  - npm i -g npm@6.7.0
  - npm install
  - npm run pretest
  - npm run prestart
script:
  - npm run webpack:prod
  - npm run test
cache:
  directories:
    - "node_modules"
