language: node.js
node_js:
  - "10"
before_script:
  - npm i -g npm@6.9.0
  - npm install
  - npm run build
script:
  - npm run webpack:prod
  - npm run sonar
  - npm run lint
cache:
  directories:
    - "node_modules"
