language: node.js
node_js:
  - "10"
before_script:
  - npm i -g npm@6.9.0
  - npm install
  - npm run build
  - npm run prestart
script:
  - npm run webpack:prod
  - npm run lint
cache:
  directories:
    - "node_modules"
