ALTER USER postgres WITH PASSWORD 'M63tT4yz5pt8KkMTUHUEj5fReZNgc5';

CREATE ROLE helpee LOGIN ENCRYPTED PASSWORD '687mvmKhhm5mV5VH89JFynMzqnzbWq' NOINHERIT VALID UNTIL 'infinity';
CREATE DATABASE helpee WITH ENCODING = 'UTF-8' OWNER = helpee;
